# Generated by Django 5.1 on 2024-09-19 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
        migrations.AddField(
            model_name='recipe',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254, validators=[django.core.validators.EmailValidator()]),
            preserve_default=False,
        ),
    ]
